# Generated by Django 4.0.5 on 2022-06-28 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=100)),
                ('aktivna', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('adresa', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('django_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifra', models.CharField(max_length=30)),
                ('ime', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=50)),
                ('cena', models.IntegerField()),
                ('kolicina', models.IntegerField()),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadaca.kategorija')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadaca.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='Prodazba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadaca.klient')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zadaca.produkt')),
            ],
        ),
    ]
